### ISSUE TITLE
How to get attributed text back from SmartString?

### ISSUE THREAD

**Issue by tkirby** [vetrek/SmartString#2]
Super cool library btw. Really takes the hassle out of constructing attributed strings and adding actions.

I'd like to use a SmartString to format a UIButton but can't figure out how to get the attributed test into <UIBUtton>.setAttirbutedTitle(...)

**Comment by vetrek** [comment]
Hi @tkirby, I'm happy to hear that you like this Library.

You are right, I've already fixed this problem with https://github.com/vetrek/SmartString/pull/3. Thanks for reporting it!
