### ISSUE TITLE
Extend tap area?

### ISSUE THREAD

**Issue by tkirby** [vetrek/SmartString#4]
Is it possible to expand the tap area for text? A single line of text in a label not so easy to tap on. There is very little vertical area on the tap.

**Comment by vetrek** [comment]
Hi @tkirby , could you please provide an example?  Increasing the 'tappable area' is possible but it could lead to weird tap behavior (e.g. tapping on a different line triggering the Tap Gesture).

**Comment by vetrek** [comment]
@tkirby This https://github.com/vetrek/SmartString/pull/5 should have fixed the problem and a new version [1.0.9](https://github.com/vetrek/SmartString/releases/tag/1.0.9)  has been released.
Please let me know if you are still experiencing this problem.

**Comment by vetrek** [comment]
Fixed by https://github.com/vetrek/SmartString/pull/5.

**Comment by vetrek** [comment]
Fixed by https://github.com/vetrek/SmartString/pull/5.

**Comment by tkirby** [comment]
Working great now,. Thanks!
